<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0bc51b5579a46a70286b2fdd25d4a0ab
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0bc51b5579a46a70286b2fdd25d4a0ab::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0bc51b5579a46a70286b2fdd25d4a0ab::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit0bc51b5579a46a70286b2fdd25d4a0ab::$classMap;

        }, null, ClassLoader::class);
    }
}
